/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmbindgenpixelrange_free: (a: number, b: number) => void;
export const wasmbindgenpixelrange_new: (a: number, b: number) => number;
export const __wbg_overlaycolor_free: (a: number, b: number) => void;
export const overlaycolor_new: (a: number, b: number, c: number, d: number) => number;
export const __wbg_overlay_free: (a: number, b: number) => void;
export const overlay_new: (a: number, b: number, c: number) => number;
export const __wbg_pixelvalue_free: (a: number, b: number) => void;
export const __wbg_get_pixelvalue_x: (a: number) => number;
export const __wbg_set_pixelvalue_x: (a: number, b: number) => void;
export const __wbg_get_pixelvalue_y: (a: number) => number;
export const __wbg_set_pixelvalue_y: (a: number, b: number) => void;
export const __wbg_get_pixelvalue_z: (a: number) => number;
export const __wbg_set_pixelvalue_z: (a: number, b: number) => void;
export const __wbg_get_pixelvalue_amplitude: (a: number) => number;
export const __wbg_set_pixelvalue_amplitude: (a: number, b: number) => void;
export const __wbg_wasmviewer_free: (a: number, b: number) => void;
export const wasmviewer_new: (a: number, b: number) => [number, number, number];
export const wasmviewer_run: (a: number) => [number, number];
export const wasmviewer_reset_view: (a: number) => any;
export const wasmviewer_set_surface: (a: number, b: number, c: number) => any;
export const wasmviewer_set_amplitude: (a: number, b: number, c: number) => any;
export const wasmviewer_get_pixel_value: (a: number) => any;
export const wasmviewer_capture_image: (a: number) => any;
export const wasmviewer_set_height_shader: (a: number) => [number, number];
export const wasmviewer_set_amplitude_shader: (a: number) => [number, number];
export const wasmviewer_set_overlays: (a: number, b: number, c: number) => [number, number];
export const wasmviewer_clear_overlays: (a: number) => [number, number];
export const wasmviewer_zoom_in: (a: number) => [number, number];
export const wasmviewer_zoom_out: (a: number) => [number, number];
export const wasmviewer_reset_orientation: (a: number) => [number, number];
export const wasmviewer_set_percentile: (a: number, b: number) => [number, number];
export const wasmviewer_set_amplitude_range: (a: number, b: number, c: number) => [number, number];
export const main: (a: number, b: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_1: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure691_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h9111653ea2b7a9f5: (a: number, b: number) => void;
export const closure698_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const closure758_externref_shim: (a: number, b: number, c: any) => void;
export const closure779_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
